### ISSUE TITLE
error message not printed correctly

### ISSUE THREAD

**Issue by stexandev** [Materials-Data-Science-and-Informatics/somesy#83]
https://github.com/Materials-Data-Science-and-Informatics/somesy/blob/77c93457ebf551fa3d77b67c2920702ae4361a9c/src/somesy/pyproject/writer.py#L193

The error message is not printed correctly:

> "The pyproject.toml file is ambiguous, either add a or section"

I expected it to be :

> "The pyproject.toml file is ambiguous, either add a [project] or [tool.poetry] section"

**Comment by mustafasoylu** [comment]
Thank you for the feedback @stexandev . I realized this problem occurs because we are using `rich` library pretty print the errors. Therefore, both traceback and error messages are checked for rich commands [in this error wrapper](https://github.com/Materials-Data-Science-and-Informatics/somesy/blob/77c93457ebf551fa3d77b67c2920702ae4361a9c/src/somesy/cli/util.py#L30). I will fix it and make release immediately.
